# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'maily' do
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for maily

  

  platform :ios, '9.0'
  target 'mailyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'maily-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for maily-tvOS

  target 'maily-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
